//
//Generate-files:
//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=.
//--go-grpc_opt=paths=source_relative auctionhouse.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: proto/auctionhouse.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_NOW_HIGHEST_BIDDER Status = 0
	Status_TOO_LOW_BID        Status = 1
	Status_EXCEPTION          Status = 2
	Status_AUCTION_ENDED      Status = 3
	Status_AUCTION_ACTIVE     Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "NOW_HIGHEST_BIDDER",
		1: "TOO_LOW_BID",
		2: "EXCEPTION",
		3: "AUCTION_ENDED",
		4: "AUCTION_ACTIVE",
	}
	Status_value = map[string]int32{
		"NOW_HIGHEST_BIDDER": 0,
		"TOO_LOW_BID":        1,
		"EXCEPTION":          2,
		"AUCTION_ENDED":      3,
		"AUCTION_ACTIVE":     4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auctionhouse_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_auctionhouse_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_auctionhouse_proto_rawDescGZIP(), []int{0}
}

// Send a new bid + subscribing
type BidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId int32 `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Amount   int32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auctionhouse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctionhouse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auctionhouse_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *BidRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Highest bidder info - highest bid, and bidder
type ResponseToQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	HighestBid int32  `protobuf:"varint,2,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	ClientId   string `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *ResponseToQuery) Reset() {
	*x = ResponseToQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auctionhouse_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseToQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseToQuery) ProtoMessage() {}

func (x *ResponseToQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctionhouse_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseToQuery.ProtoReflect.Descriptor instead.
func (*ResponseToQuery) Descriptor() ([]byte, []int) {
	return file_proto_auctionhouse_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseToQuery) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_NOW_HIGHEST_BIDDER
}

func (x *ResponseToQuery) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ResponseToQuery) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Message for prompting asking for highest bidder
type QueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auctionhouse_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctionhouse_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_proto_auctionhouse_proto_rawDescGZIP(), []int{2}
}

// Was bid successful?
type StatusOfBid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	HighestBid int32    `protobuf:"varint,2,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	Ports      []string `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *StatusOfBid) Reset() {
	*x = StatusOfBid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_auctionhouse_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusOfBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusOfBid) ProtoMessage() {}

func (x *StatusOfBid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auctionhouse_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusOfBid.ProtoReflect.Descriptor instead.
func (*StatusOfBid) Descriptor() ([]byte, []int) {
	return file_proto_auctionhouse_proto_rawDescGZIP(), []int{3}
}

func (x *StatusOfBid) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_NOW_HIGHEST_BIDDER
}

func (x *StatusOfBid) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *StatusOfBid) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_proto_auctionhouse_proto protoreflect.FileDescriptor

var file_proto_auctionhouse_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x40, 0x0a, 0x0a, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54,
	0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6a, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4f, 0x66, 0x42, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x2a, 0x67, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16,
	0x0a, 0x12, 0x4e, 0x4f, 0x57, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x45, 0x53, 0x54, 0x5f, 0x42, 0x49,
	0x44, 0x44, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x4f, 0x4f, 0x5f, 0x4c, 0x4f,
	0x57, 0x5f, 0x42, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x58, 0x43, 0x45, 0x50,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x55, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x55, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x04, 0x32, 0x7d, 0x0a,
	0x13, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x54, 0x6f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x03,
	0x42, 0x69, 0x64, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4f, 0x66, 0x42, 0x69, 0x64, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_auctionhouse_proto_rawDescOnce sync.Once
	file_proto_auctionhouse_proto_rawDescData = file_proto_auctionhouse_proto_rawDesc
)

func file_proto_auctionhouse_proto_rawDescGZIP() []byte {
	file_proto_auctionhouse_proto_rawDescOnce.Do(func() {
		file_proto_auctionhouse_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_auctionhouse_proto_rawDescData)
	})
	return file_proto_auctionhouse_proto_rawDescData
}

var file_proto_auctionhouse_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_auctionhouse_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_auctionhouse_proto_goTypes = []interface{}{
	(Status)(0),             // 0: proto.Status
	(*BidRequest)(nil),      // 1: proto.BidRequest
	(*ResponseToQuery)(nil), // 2: proto.ResponseToQuery
	(*QueryResult)(nil),     // 3: proto.QueryResult
	(*StatusOfBid)(nil),     // 4: proto.StatusOfBid
}
var file_proto_auctionhouse_proto_depIdxs = []int32{
	0, // 0: proto.ResponseToQuery.status:type_name -> proto.Status
	0, // 1: proto.StatusOfBid.status:type_name -> proto.Status
	3, // 2: proto.AuctionhouseService.Result:input_type -> proto.QueryResult
	1, // 3: proto.AuctionhouseService.Bid:input_type -> proto.BidRequest
	2, // 4: proto.AuctionhouseService.Result:output_type -> proto.ResponseToQuery
	4, // 5: proto.AuctionhouseService.Bid:output_type -> proto.StatusOfBid
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_auctionhouse_proto_init() }
func file_proto_auctionhouse_proto_init() {
	if File_proto_auctionhouse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_auctionhouse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auctionhouse_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseToQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auctionhouse_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_auctionhouse_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusOfBid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_auctionhouse_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auctionhouse_proto_goTypes,
		DependencyIndexes: file_proto_auctionhouse_proto_depIdxs,
		EnumInfos:         file_proto_auctionhouse_proto_enumTypes,
		MessageInfos:      file_proto_auctionhouse_proto_msgTypes,
	}.Build()
	File_proto_auctionhouse_proto = out.File
	file_proto_auctionhouse_proto_rawDesc = nil
	file_proto_auctionhouse_proto_goTypes = nil
	file_proto_auctionhouse_proto_depIdxs = nil
}
